### ISSUE TITLE
ـ [اقتراح] ازالة موقع المبرمج العربي

### ISSUE THREAD

**Issue by X7md** [aissa-bouguern/arabic-programming-blogs#8]
يبدو لي وكأن الموقع عبارة عن مجرد بوت يقوم بنسخ مقالات من الانترنت وترجمتها آليًا، غير أنه ممتلئ بإعلانات ادسنس من كل حدبٍ وصوب... غير أنه غير موسوعي وعشوائي جدًا

[arabicprogrammer.com](https://www.arabicprogrammer.com/article/79411219265/)

**Comment by aissa-bouguern** [comment]
solved
